import { useEffect, useRef, useState } from 'react';
import type { Project, ImageMetadata, DSMStatistics, TerrainInspection, ValidationMetrics, CalibrationResult } from '../types';
import { projectApi } from '../services/api';

interface Props { project: Project | null; inspection?: TerrainInspection | null; onProjectChange?: (p: Project) => void; }
type Tab='overview'|'calibration'|'validation'|'exports'; type Preview='dsm'|'depth'|'slope';

export function InfoPanel({project,inspection,onProjectChange}:Props){
  const [metadata,setMetadata]=useState<ImageMetadata|null>(null); const [stats,setStats]=useState<DSMStatistics|null>(null); const [validation,setValidation]=useState<ValidationMetrics|null>(null); const [cal,setCal]=useState<CalibrationResult|null>(null); const [calHistory,setCalHistory]=useState<any[]>([]); const [validationHistory,setValidationHistory]=useState<any[]>([]);
  const [tab,setTab]=useState<Tab>('overview'); const [preview,setPreview]=useState<Preview>('dsm'); const [busy,setBusy]=useState(''); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [errorMapKey,setErrorMapKey]=useState(0);
  const [gcp,setGcp]=useState([{pixel_x:'',pixel_y:'',reference_elevation:''},{pixel_x:'',pixel_y:'',reference_elevation:''},{pixel_x:'',pixel_y:'',reference_elevation:''}]);
  const demRef=useRef<HTMLInputElement>(null); const refRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{setMetadata(null);setStats(null);setValidation(null);setCal(null);setCalHistory([]);setValidationHistory([]);setMessage('');setError('');setTab('overview');if(project&&['READY','VALIDATED'].includes(project.state)){Promise.all([projectApi.getMetadata(project.project_id).then(setMetadata).catch(()=>{}),projectApi.getStatistics(project.project_id).then(setStats).catch(()=>{}),projectApi.getReport(project.project_id).then(r=>{if(r.validation_metrics)setValidation(r.validation_metrics);if(r.calibration_info)setCal(r.calibration_info);setCalHistory(r.calibration_history||[]);setValidationHistory(r.validation_history||[])}).catch(()=>{})])}},[project?.project_id,project?.state]);
  if(!project)return <div className="info-empty"><span className="panel-kicker">ANALYSIS</span><div className="info-empty-title">Nothing loaded</div><p>Create a project, upload imagery and run reconstruction to inspect results.</p></div>;
  const metric=project.reconstruction_mode==='metric'; const georef=project.is_georeferenced; const canValidate=!georef||metric; const canCalibrate=['READY','VALIDATED'].includes(project.state); const previewUrl=preview==='dsm'?projectApi.getDsmUrl(project.project_id):preview==='depth'?projectApi.getDepthUrl(project.project_id):projectApi.getDownloadUrl(project.project_id,'slope');
  const refresh=async()=>{onProjectChange?.(await projectApi.get(project.project_id))};
  const download=async(artifact:string)=>{try{setBusy(`download:${artifact}`);setError('');const blob=await projectApi.downloadArtifact(project.project_id,artifact);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=artifact==='dsm'?(metric?'depthwizard_metric_dsm.tif':'depthwizard_relative_dsm.tif'):artifact==='metric_dsm'?'depthwizard_metric_dsm.tif':artifact==='mesh'?'depthwizard_terrain.glb':artifact==='error_map'?'depthwizard_error_map.png':artifact==='report_html'?'depthwizard_report.html':artifact==='report'?'depthwizard_report.json':artifact==='depth'?'depthwizard_depth.png':`depthwizard_${artifact}`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}catch(e:any){setError(e.response?.data?.detail||`Export failed: ${artifact}`)}finally{setBusy('')}};
  const doDem=async()=>{const f=demRef.current?.files?.[0];if(!f){setError('Choose a reference DEM GeoTIFF first.');return}try{setBusy('dem');setError('');setMessage('Aligning DEM to the input CRS/grid and fitting elevation scale…');const r=await projectApi.calibrateDem(project.project_id,f);setCal(r);setMessage(`DEM calibration complete · residual RMSE ${Number(r.rmse||0).toFixed(3)} m`);await refresh()}catch(e:any){setError(e.response?.data?.detail||'DEM calibration failed')}finally{setBusy('')}};
  const doGcp=async()=>{try{setBusy('gcp');setError('');const r=await projectApi.calibrate(project.project_id,'gcp',gcp.map(x=>({pixel_x:Number(x.pixel_x),pixel_y:Number(x.pixel_y),reference_elevation:Number(x.reference_elevation)})));setCal(r);setMessage(`GCP calibration complete · residual RMSE ${Number(r.rmse||0).toFixed(3)} m`);await refresh()}catch(e:any){setError(e.response?.data?.detail||'GCP calibration failed')}finally{setBusy('')}};
  const doValidate=async()=>{const f=refRef.current?.files?.[0];if(!f){setError('Choose a reference DSM/DEM GeoTIFF first.');return}try{setBusy('validate');setError('');setMessage(metric?'Comparing calibrated DSM against the aligned reference surface…':'Comparing the relative surface against the supplied reference…');const r=await projectApi.validate(project.project_id,f);setValidation(r);setErrorMapKey(k=>k+1);setMessage('Validation complete. Metrics are computed from overlapping valid pixels.');await refresh()}catch(e:any){setError(e.response?.data?.detail||'Validation failed')}finally{setBusy('')}};
  const tabs:[Tab,string,string][]= [['overview','01','Overview'],['calibration','02','Calibration'],['validation','03','Validation'],['exports','04','Exports']];
  return <div className="info-content">
    <div className="panel-section info-hero"><div className="panel-kicker">PROJECT MODE</div><div className={`mode-pill ${metric?'metric':'relative'}`}><span>{metric?'✓':georef?'◎':'◇'}</span><div><b>{metric?'METRIC MODE':georef?'GEOREFERENCED MODE':'RELATIVE MODE'}</b><small>{metric?'Calibrated elevation · metres':georef?'CRS detected · calibration required':'PNG/JPG · normalized elevation'}</small></div></div><div className="project-id">{project.project_id}</div>{metadata&&<div className="metadata-line">{metadata.width} × {metadata.height} px · {metadata.channels} band(s){metadata.epsg?` · EPSG:${metadata.epsg}`:''}</div>}</div>
    <div className="info-tabs">{tabs.map(([id,n,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><span>{n}</span>{label}</button>)}</div>
    {tab==='overview'&&<>
      {stats&&<div className="panel-section"><div className="section-head"><span className="panel-kicker">DSM SURFACE</span><span className={`mini-label ${metric?'metric-label':''}`}>{metric?'METRIC · METRES':'RELATIVE · NORMALIZED'}</span></div><div className="metric-grid"><div><span>MIN</span><strong>{stats.min_elevation.toFixed(2)}</strong></div><div><span>MAX</span><strong>{stats.max_elevation.toFixed(2)}</strong></div><div><span>MEAN</span><strong>{stats.mean_elevation.toFixed(2)}</strong></div><div><span>RANGE</span><strong>{stats.elevation_range.toFixed(2)}</strong></div></div><div className="quality-row"><span>Surface validity</span><b>{stats.valid_pixel_percentage.toFixed(1)}%</b></div><div className="quality-row"><span>Mean slope</span><b>{(stats.slope_mean??0).toFixed(2)}°</b></div><div className="quality-row"><span>Elevation unit</span><b>{metric?'m':'relative'}</b></div>{metadata?.resolution&&<div className="quality-row"><span>Pixel size</span><b>{Math.abs(metadata.resolution[0]).toFixed(3)} × {Math.abs(metadata.resolution[1]).toFixed(3)}</b></div>}</div>}
      <div className="panel-section preview-section"><div className="section-head"><span className="panel-kicker">SURFACE PREVIEW</span><span className="mini-label">RASTER</span></div><div className="segmented preview-tabs"><button className={preview==='dsm'?'active':''} onClick={()=>setPreview('dsm')}>DSM</button><button className={preview==='depth'?'active':''} onClick={()=>setPreview('depth')}>Depth</button><button className={preview==='slope'?'active':''} onClick={()=>setPreview('slope')}>Slope</button></div><div className="preview-frame"><img key={`${previewUrl}-${errorMapKey}`} src={previewUrl} alt={`${preview} preview`} onError={e=>{e.currentTarget.style.opacity='.22'}}/></div></div>
      {inspection&&<div className="panel-section inspect-card"><div className="section-head"><span className="panel-kicker">POINT INSPECTION</span><span className="mini-label">LIVE</span></div><div className="metric-grid"><div><span>ELEVATION</span><strong>{inspection.elevation.toFixed(2)} {inspection.unit==='m'?'m':''}</strong></div><div><span>SLOPE</span><strong>{(inspection.slope??0).toFixed(2)}°</strong></div><div><span>PIXEL X</span><strong>{inspection.pixel_x??inspection.x.toFixed(0)}</strong></div><div><span>PIXEL Y</span><strong>{inspection.pixel_y??inspection.y.toFixed(0)}</strong></div></div>{metric&&<div className="inspect-world">World position · {inspection.x.toFixed(3)}, {inspection.y.toFixed(3)}</div>}</div>}
      <div className="panel-section"><div className="section-head"><span className="panel-kicker">WHAT THIS MODE MEANS</span></div><div className="explain-card"><div><b>{metric?'Metric elevation is active':'Relative elevation is active'}</b><p>{metric?'The DSM has been mapped to real-world elevation using a DEM or GCPs. Validation can now report metric error in metres.':'This surface is normalized by the monocular model. It is suitable for 3D exploration, but absolute height in metres is not available without calibration.'}</p></div></div></div>
    </>}
    {tab==='calibration'&&<div className="panel-section"><div className="section-head"><span className="panel-kicker">DEM / GCP CALIBRATION</span><span className="mini-label">METRIC OUTPUT</span></div>{!georef?<div className="locked-card"><b>Calibration is locked for this project</b><p>Upload a georeferenced GeoTIFF to preserve CRS, transform and pixel size. PNG/JPG projects remain relative.</p></div>:<><div className="calibration-flow"><div className="flow-step"><b>1</b><span>Relative AI depth</span></div><i>→</i><div className="flow-step"><b>2</b><span>DEM or GCP scale</span></div><i>→</i><div className="flow-step"><b>3</b><span>Metric DSM</span></div></div><div className="calibration-note"><b>DEM method</b><br/>Upload a lower-resolution reference DEM. DepthWizard reprojects it to the input GeoTIFF grid and fits a scale + offset using overlapping valid pixels.</div><input ref={demRef} className="file-mini" type="file" accept=".tif,.tiff"/><button className="btn btn-primary btn-full" disabled={!!busy||!canCalibrate} onClick={doDem}>{busy==='dem'?'Calibrating…':'Calibrate with DEM'}</button><div className="divider-label"><span>OR USE 3 GROUND CONTROL POINTS</span></div><div className="gcp-grid">{gcp.map((v,i)=><div className="gcp-row" key={i}><input type="number" placeholder={`Pixel X${i+1}`} value={v.pixel_x} onChange={e=>setGcp(a=>a.map((q,j)=>j===i?{...q,pixel_x:e.target.value}:q))}/><input type="number" placeholder={`Pixel Y${i+1}`} value={v.pixel_y} onChange={e=>setGcp(a=>a.map((q,j)=>j===i?{...q,pixel_y:e.target.value}:q))}/><input type="number" placeholder="Elevation m" value={v.reference_elevation} onChange={e=>setGcp(a=>a.map((q,j)=>j===i?{...q,reference_elevation:e.target.value}:q))}/></div>)}</div><button className="btn btn-secondary btn-full" disabled={!!busy||!gcp.every(x=>x.pixel_x&&x.pixel_y&&x.reference_elevation)||!canCalibrate} onClick={doGcp}>{busy==='gcp'?'Calibrating…':'Apply 3-point GCP calibration'}</button>{cal&&<div className="calibration-result"><div><span>SCALE</span><b>{Number(cal.scale||0).toFixed(5)}</b></div><div><span>OFFSET</span><b>{Number(cal.offset||0).toFixed(3)} m</b></div><div><span>RESIDUAL RMSE</span><b>{Number(cal.rmse||0).toFixed(3)} m</b></div></div>}{calHistory.length>0&&<div className="analysis-history"><div className="history-title">CALIBRATION HISTORY <span>{calHistory.length} run{calHistory.length===1?"":"s"}</span></div>{calHistory.slice(0,5).map((h:any)=><div className="history-row" key={h.run_id}><div><b>{h.run_id}</b><small>{String(h.method||"calibration").toUpperCase()} · {new Date(h.created_at).toLocaleString()}</small></div><strong>{Number(h.rmse||0).toFixed(3)} m RMSE</strong></div>)}</div>}</>}</div>}
    {tab==='validation'&&<div className="panel-section"><div className="section-head"><span className="panel-kicker">REFERENCE VALIDATION</span><span className="mini-label">DSM / DEM / LIDAR</span></div><div className="validation-explain"><div className="validation-step"><b>01</b><span>Upload reference</span><small>Ground-truth DSM/DEM</small></div><div className="validation-step"><b>02</b><span>Align grids</span><small>CRS + resolution</small></div><div className="validation-step"><b>03</b><span>Compute error</span><small>RMSE · MAE · R² · R</small></div></div>{!canValidate?<div className="locked-card"><b>Calibration required before metric validation</b><p>This GeoTIFF is georeferenced but still relative. Go to Calibration and apply DEM or GCP scaling first.</p><button className="btn btn-secondary btn-full" onClick={()=>setTab('calibration')}>Open calibration</button></div>:<><div className="calibration-note">Choose a spatially corresponding reference surface. For a metric result, use a reference DEM/DSM in a compatible CRS. The backend aligns the reference to the predicted DSM grid and ignores NoData pixels.</div><input ref={refRef} className="file-mini" type="file" accept=".tif,.tiff"/><button className="btn btn-primary btn-full" disabled={!!busy||!canCalibrate} onClick={doValidate}>{busy==='validate'?'Validating…':'Run reference validation'}</button>{validation&&<><div className="validation-grid"><div><span>RMSE</span><strong>{validation.rmse.toFixed(3)} {metric?'m':'relative'}</strong></div><div><span>MAE</span><strong>{validation.mae.toFixed(3)} {metric?'m':'relative'}</strong></div><div><span>R²</span><strong>{validation.r2.toFixed(3)}</strong></div><div><span>PEARSON R</span><strong>{validation.pearson_correlation.toFixed(3)}</strong></div></div><div className="validation-extra"><span>Bias {validation.bias.toFixed(3)} {metric?'m':'rel.'}</span><span>{validation.valid_pixel_percentage.toFixed(1)}% valid</span></div>{validationHistory.length>0&&<div className="analysis-history"><div className="history-title">VALIDATION HISTORY <span>{validationHistory.length} run{validationHistory.length===1?"":"s"}</span></div>{validationHistory.slice(0,5).map((h:any)=><div className="history-row" key={h.run_id}><div><b>{h.run_id}</b><small>{new Date(h.created_at).toLocaleString()}</small></div><strong>{Number(h.rmse||0).toFixed(3)} m RMSE · {Number(h.valid_pixel_percentage||0).toFixed(1)}%</strong></div>)}</div>}<div className="error-map-head"><b>SPATIAL ERROR MAP</b><span>Predicted − reference</span></div><img className="error-map" key={errorMapKey} src={`${projectApi.getErrorMapUrl(project.project_id)}?v=${errorMapKey}`} alt="Predicted minus reference error map"/><div className="legend"><span>Under</span><i className="legend-blue"/><i className="legend-white"/><i className="legend-red"/><span>Over</span></div></>}</>}</div>}
    {tab==='exports'&&<div className="panel-section"><div className="section-head"><span className="panel-kicker">EXPORT CENTER</span><span className="mini-label">GEOSPATIAL + 3D</span></div><div className="export-grid"><button className="export-card" onClick={()=>download('dsm')} disabled={!!busy}><b>DSM GeoTIFF</b><span>{metric?'Metric elevation':'Relative elevation'}</span><i>↓</i></button><button className={`export-card ${metric?'':'disabled-card'}`} onClick={()=>metric&&download('metric_dsm')} disabled={!metric||!!busy}><b>Metric DSM</b><span>{metric?'GeoTIFF · metres':'Requires calibration'}</span><i>{metric?'↓':'🔒'}</i></button><button className="export-card" onClick={()=>download('depth')} disabled={!!busy}><b>Depth preview</b><span>PNG visualization</span><i>↓</i></button><button className="export-card" onClick={()=>download('mesh')} disabled={!!busy}><b>Terrain mesh</b><span>GLB · textured 3D</span><i>↓</i></button><button className={`export-card ${validation?'':'disabled-card'}`} onClick={()=>validation&&download('error_map')} disabled={!validation||!!busy}><b>Error map</b><span>{validation?'PNG · validation result':'Requires validation'}</span><i>{validation?'↓':'🔒'}</i></button><button className="export-card" onClick={()=>download('report')} disabled={!!busy}><b>Analysis report</b><span>JSON · reproducibility</span><i>↓</i></button><button className="export-card" onClick={()=>download('report_html')} disabled={!!busy}><b>Presentation report</b><span>HTML · shareable</span><i>↓</i></button></div><div className="export-note">Exports are state-aware: metric DSM is locked until calibration; error-map export is locked until reference validation completes.</div></div>}
    {(message||error)&&<div className={`notice-card ${error?'notice-error':''}`}><b>{error?'Action needs attention':'Status'}</b><span>{error||message}</span></div>}
  </div>;
}
