import React, { useEffect, useRef, useState } from 'react';
import type { Project } from '../types';
import { projectApi } from '../services/api';

interface Props { project: Project | null; onProjectChange: (project: Project | null) => void; }

export function ProjectPanel({ project, onProjectChange }: Props) {
  const fileInputRef=useRef<HTMLInputElement>(null); const pollRef=useRef<number|null>(null);
  const [projectName,setProjectName]=useState(''); const [loading,setLoading]=useState(false); const [dragging,setDragging]=useState(false); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{const saved=localStorage.getItem('depthwizard.projectId');if(!saved||project)return;projectApi.getStatus(saved).then(onProjectChange).catch(()=>localStorage.removeItem('depthwizard.projectId'))},[onProjectChange,project]);
  useEffect(()=>{if(project)localStorage.setItem('depthwizard.projectId',project.project_id)},[project]);
  useEffect(()=>()=>{if(pollRef.current!==null)clearInterval(pollRef.current)},[]);
  const create=async()=>{if(!projectName.trim()||loading)return;setLoading(true);setError(null);try{onProjectChange(await projectApi.create(projectName.trim(),'Single-view elevation reconstruction workspace'));setProjectName('')}catch(e:any){setError(e.response?.data?.detail||'Failed to create project')}finally{setLoading(false)}};
  const upload=async(file:File)=>{if(!project||loading)return;if(!/\.(jpg|jpeg|png|tif|tiff)$/i.test(file.name)){setError('Use JPG, PNG or GeoTIFF (.tif/.tiff).');return}setLoading(true);setError(null);try{await projectApi.upload(project.project_id,file);onProjectChange(await projectApi.get(project.project_id))}catch(e:any){setError(e.response?.data?.detail||'Upload failed')}finally{setLoading(false)}};
  const process=async()=>{if(!project||loading)return;setLoading(true);setError(null);try{await projectApi.process(project.project_id);pollRef.current=window.setInterval(async()=>{try{const p=await projectApi.getStatus(project.project_id);onProjectChange(p);if(['READY','FAILED','VALIDATED'].includes(p.state)){if(pollRef.current!==null)clearInterval(pollRef.current);pollRef.current=null;setLoading(false)}}catch{if(pollRef.current!==null)clearInterval(pollRef.current);pollRef.current=null;setLoading(false);setError('Lost connection while checking reconstruction status.')}} ,1000)}catch(e:any){setError(e.response?.data?.detail||'Processing failed');setLoading(false)}};
  const reset=()=>{if(pollRef.current!==null)clearInterval(pollRef.current);pollRef.current=null;localStorage.removeItem('depthwizard.projectId');onProjectChange(null);setProjectName('');setError(null)};
  const badge=(s:string)=><span className={`state-badge ${s==='FAILED'?'failed':['READY','VALIDATED'].includes(s)?'ready':['NEW','UPLOADED'].includes(s)?'neutral':'processing'}`}><i/>{s.replace(/_/g,' ')}</span>;
  const mode=project?.reconstruction_mode==='metric'?'metric':project?.is_georeferenced?'georef':'relative';
  return <div className="project-content">
    <div className="panel-intro"><span className="panel-kicker">WORKSPACE</span><h2>{project?'Project controls':'Create a workspace'}</h2><p>{project?'Manage input, reconstruction and analysis.':'Turn a single image into an explorable elevation surface.'}</p></div>
    {!project&&<div className="panel-section create-card"><label className="field-label">PROJECT NAME</label><input className="input" placeholder="e.g. Campus elevation study" value={projectName} onChange={e=>setProjectName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&create()} autoFocus/><button className="btn btn-primary btn-full" onClick={create} disabled={!projectName.trim()||loading}>{loading?'Creating…':'Create project'} <span>→</span></button></div>}
    {project&&<>
      <div className="panel-section project-card"><div className="section-head"><span className="panel-kicker">ACTIVE PROJECT</span>{badge(project.state)}</div><div className="project-name">{project.name}</div><div className="project-id">ID · {project.project_id}</div></div>
      <div className={`mode-card mode-${mode}`}><div className="mode-head"><span className="mode-icon">{mode==='metric'?'✓':mode==='georef'?'◎':'◇'}</span><div><span className="panel-kicker">RECONSTRUCTION MODE</span><strong>{mode==='metric'?'METRIC MODE':mode==='georef'?'GEOREFERENCED MODE':'RELATIVE MODE'}</strong></div></div><p>{mode==='metric'?'Calibrated real-world elevation. DSM and validation are metric.':mode==='georef'?'GeoTIFF detected. Calibrate with DEM or GCP to unlock metric DSM.':'PNG/JPG workflow. Relative elevation is valid for visualization, not metres.'}</p><div className="mode-step"><span className="step-dot done">1</span><span>Input</span><span className="step-line"/><span className={`step-dot ${project.state==='READY'||project.state==='VALIDATED'?'done':''}`}>2</span><span>AI depth</span><span className="step-line"/><span className={`step-dot ${mode==='metric'?'done':''}`}>3</span><span>Metric</span></div></div>
      {(project.state==='NEW'||project.state==='UPLOADED')&&<div className="panel-section"><div className="section-head"><span className="panel-kicker">INPUT</span><span className="mini-label">JPG · PNG · GEOTIFF</span></div><button className={`upload-zone ${dragging?'dragging':''}`} onClick={()=>fileInputRef.current?.click()} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={async e=>{e.preventDefault();setDragging(false);const f=e.dataTransfer.files?.[0];if(f)await upload(f)}} disabled={loading}><span className="upload-icon">↑</span><span><b>{project.state==='UPLOADED'?'Replace source image':'Choose source image'}</b><small>GeoTIFF preserves CRS and pixel resolution</small></span></button><input ref={fileInputRef} type="file" accept=".jpg,.jpeg,.png,.tif,.tiff" hidden onChange={e=>{const f=e.target.files?.[0];if(f)upload(f);e.target.value=''}}/></div>}
      {project.state==='UPLOADED'&&<div className="panel-section action-card"><div className="action-copy"><span className="action-icon">✦</span><div><b>Ready to reconstruct</b><small>High-accuracy tiled depth inference → surface → slope → textured 3D terrain</small></div></div><button className="btn btn-primary btn-full" onClick={process} disabled={loading}>{loading?'Processing…':'Run high-accuracy reconstruction'} <span>→</span></button></div>}
      {loading&&<div className="panel-section"><div className="section-head"><span className="panel-kicker">PIPELINE</span><strong className="progress-value">{Math.round((project.progress||0)*100)}%</strong></div><div className="progress-bar"><div className="progress-fill" style={{width:`${Math.max(3,(project.progress||0)*100)}%`}}/></div><div className="progress-copy">{project.message||'Processing terrain reconstruction…'}</div></div>}
      {(project.state==='READY'||project.state==='VALIDATED')&&<div className="panel-section quick-actions"><div className="section-head"><span className="panel-kicker">WORKFLOW</span><span className="mini-label">NEXT STEPS</span></div><div className="workflow-list"><div className={mode==='georef'?'workflow-item current':'workflow-item done'}><b>01</b><span>Inspect 3D terrain</span><i>✓</i></div><div className={mode==='georef'?'workflow-item current':'workflow-item'}><b>02</b><span>{mode==='metric'?'Metric DSM ready':'Calibration / mode'}</span><i>{mode==='metric'?'✓':'→'}</i></div><div className="workflow-item"><b>03</b><span>Reference validation</span><i>→</i></div><div className="workflow-item"><b>04</b><span>Export report & surfaces</span><i>→</i></div></div></div>}
      {(project.state==='READY'||project.state==='VALIDATED')&&<div className="panel-section benchmark-card"><div className="section-head"><span className="panel-kicker">BENCHMARK</span><span className="mini-label">REAL DATA ONLY</span></div><p>Evaluate calibrated DSMs across the five target landscapes. DepthWizard includes a manifest template and metric runner; enter only measured reference results.</p><div className="benchmark-tags"><span>Urban</span><span>Sparse</span><span>Hilly</span><span>Forested</span><span>Mixed</span></div><small>Run <b>scripts\benchmark_metrics.py</b> with a completed benchmark CSV.</small></div>}
      <div className="panel-section reset-section"><button className="btn btn-ghost btn-full" onClick={reset}>Reset workspace</button></div>
    </>}
    {error&&<div className="error-card"><span>!</span><div><b>Something went wrong</b><p>{error}</p></div></div>}
  </div>;
}
