import { Canvas, useThree } from '@react-three/fiber';
import { FlyControls, OrbitControls } from '@react-three/drei';
import { useCallback, useEffect, useLayoutEffect, useRef, useState } from 'react';
import type { Project, TerrainInspection, HistoryResponse, ImageMetadata, DSMStatistics } from '../types';
import { projectApi } from '../services/api';
import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';

interface Props { project:Project|null; onInspection?:(v:TerrainInspection|null)=>void; inspection?:TerrainInspection|null; history?:HistoryResponse|null; meta?:ImageMetadata|null; stats?:DSMStatistics|null; gridVisible:boolean; setGridVisible:(v:boolean)=>void; panelOpen:boolean; setPanelOpen:(v:boolean)=>void; }
type ViewMode='orbit'|'fly';
type RenderMode='rgb'|'elevation'|'relief'|'slope'|'wire';
type CameraPreset='isometric'|'top'|'front'|'side';

function prepareTerrain(scene:THREE.Object3D){
  scene.traverse(c=>{
    if(!(c instanceof THREE.Mesh))return;
    c.frustumCulled=false;c.castShadow=true;c.receiveShadow=true;
    c.geometry.computeBoundingBox();c.geometry.computeBoundingSphere();c.geometry.computeVertexNormals();
    const mats=Array.isArray(c.material)?c.material:[c.material];
    const cloned=mats.map(src=>{const m=src.clone() as THREE.MeshStandardMaterial;m.userData.dwOriginalMap=m.map??null;m.side=THREE.DoubleSide;m.roughness=.84;m.metalness=.01;return m});
    c.material=Array.isArray(c.material)?cloned:cloned[0];
  });
  const box=new THREE.Box3().setFromObject(scene);const size=box.getSize(new THREE.Vector3());const center=box.getCenter(new THREE.Vector3());
  const footprint=Math.max(size.x,size.z,1);const range=Math.max(size.y,1e-6);const targetWidth=21;const xyScale=targetWidth/footprint;
  scene.position.sub(center);scene.position.y+=size.y/2;scene.scale.set(xyScale,(targetWidth*.46)/range,xyScale);scene.updateMatrixWorld(true);
  const finalBox=new THREE.Box3().setFromObject(scene);scene.position.y-=finalBox.min.y;scene.updateMatrixWorld(true);scene.userData.dwReady=true;
}
function colorize(scene:THREE.Object3D,mode:'elevation'|'slope'){
  scene.traverse(c=>{
    if(!(c instanceof THREE.Mesh))return;const pos=c.geometry.getAttribute('position');if(!pos)return;
    if(mode==='slope'&&!c.geometry.getAttribute('normal'))c.geometry.computeVertexNormals();const n=c.geometry.getAttribute('normal');let min=Infinity,max=-Infinity;
    if(mode==='elevation')for(let i=0;i<pos.count;i++){min=Math.min(min,pos.getY(i));max=Math.max(max,pos.getY(i))}
    const range=Math.max(max-min,1e-6),colors=new Float32Array(pos.count*3),col=new THREE.Color();
    for(let i=0;i<pos.count;i++){const t=mode==='elevation'?THREE.MathUtils.clamp((pos.getY(i)-min)/range,0,1):THREE.MathUtils.clamp((1-Math.max(0,n?.getY(i)??1))*1.7,0,1);col.setHSL(.62-.58*t,.78,.5+.08*(1-t));colors[i*3]=col.r;colors[i*3+1]=col.g;colors[i*3+2]=col.b}
    c.geometry.setAttribute('color',new THREE.BufferAttribute(colors,3));
  });
}
function SurfaceMaterial({scene,mode}:{scene:THREE.Object3D;mode:RenderMode}){useEffect(()=>{if(mode==='elevation'||mode==='slope')colorize(scene,mode);scene.traverse(c=>{if(!(c instanceof THREE.Mesh))return;const mats=Array.isArray(c.material)?c.material:[c.material];mats.forEach(src=>{const m=src as THREE.MeshStandardMaterial;const original=(m.userData.dwOriginalMap as THREE.Texture|null)??null;m.wireframe=mode==='wire';m.vertexColors=mode==='elevation'||mode==='slope';m.map=mode==='rgb'?original:null;m.color.set(mode==='wire'?'#65d4ff':mode==='relief'?'#d7e0e5':'#ffffff');m.needsUpdate=true})})},[scene,mode]);return null}
function Terrain({url,renderMode,onLoaded,onError,onClick}:{url:string;renderMode:RenderMode;onLoaded:(o:THREE.Object3D)=>void;onError:(s:string)=>void;onClick:(e:THREE.Intersection)=>void}){const [object,setObject]=useState<THREE.Object3D|null>(null);useEffect(()=>{let alive=true;setObject(null);const loader=new GLTFLoader();loader.load(`${url}?v=30`,g=>{if(!alive)return;try{let count=0;g.scene.traverse(c=>{if(c instanceof THREE.Mesh)count++});if(!count)throw new Error('Generated GLB contains no terrain mesh.');prepareTerrain(g.scene);setObject(g.scene);onLoaded(g.scene)}catch(e){onError(e instanceof Error?e.message:'Terrain preparation failed.')}},undefined,e=>onError(`Unable to load terrain GLB${e instanceof Error?`: ${e.message}`:'.'}`));return()=>{alive=false}},[url,onLoaded,onError]);return object?<><primitive object={object} onClick={(e:any)=>{e.stopPropagation();onClick(e)}}/><SurfaceMaterial scene={object} mode={renderMode}/></>:null}
function CameraRig({target,resetToken,preset}:{target:THREE.Object3D|null;resetToken:number;preset:CameraPreset}){const {camera}=useThree();const controls=useRef<any>(null);useEffect(()=>{if(!target)return;target.updateWorldMatrix(true,true);const box=new THREE.Box3().setFromObject(target),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),d=Math.max(size.x,size.y,size.z)*1.22,cam=camera as THREE.PerspectiveCamera;cam.near=.01;cam.far=Math.max(d*30,500);if(preset==='top')cam.position.set(center.x,center.y+d*1.25,center.z+.01);else if(preset==='front')cam.position.set(center.x,center.y+d*.22,center.z+d*1.55);else if(preset==='side')cam.position.set(center.x+d*1.55,center.y+d*.22,center.z);else cam.position.set(center.x+d*.88,center.y+d*.72,center.z+d*.88);cam.lookAt(center);cam.updateProjectionMatrix();if(controls.current){controls.current.target.copy(center);controls.current.minDistance=Math.max(d*.06,.25);controls.current.maxDistance=Math.max(d*7,60);controls.current.update()}},[target,resetToken,preset,camera]);return <OrbitControls ref={controls} makeDefault enableDamping dampingFactor={.08} screenSpacePanning minPolarAngle={.03} maxPolarAngle={Math.PI*.495}/>}
function SceneGrid({terrain,visible}:{terrain:THREE.Object3D|null;visible:boolean}){const [layout,setLayout]=useState<{size:number;x:number;y:number;z:number}|null>(null);useLayoutEffect(()=>{if(!terrain){setLayout(null);return}terrain.updateWorldMatrix(true,true);const box=new THREE.Box3().setFromObject(terrain);const size=box.getSize(new THREE.Vector3());const center=box.getCenter(new THREE.Vector3());setLayout({size:Math.max(size.x,size.z)*1.28,x:center.x,y:box.min.y-.018,z:center.z})},[terrain]);if(!visible||!layout)return null;return <group position={[layout.x,layout.y,layout.z]}><gridHelper args={[layout.size,32,'#426579','#182e3b']}/><mesh rotation={[-Math.PI/2,0,0]} position={[0,-.008,0]}><planeGeometry args={[layout.size,layout.size]}/><meshBasicMaterial color="#071018" transparent opacity={.26} depthWrite={false}/></mesh><axesHelper args={[Math.min(layout.size*.10,2.2)]}/></group>}
function Contours({terrain,visible}:{terrain:THREE.Object3D|null;visible:boolean}){const [lines,setLines]=useState<THREE.LineSegments|null>(null);useEffect(()=>{if(!terrain||!visible){setLines(null);return}const segments:number[]=[];let min=Infinity,max=-Infinity;terrain.traverse(c=>{if(c instanceof THREE.Mesh){const p=c.geometry.getAttribute('position');for(let i=0;i<p.count;i++){const y=p.getY(i);min=Math.min(min,y);max=Math.max(max,y)}}});if(!Number.isFinite(min)||!Number.isFinite(max)||max-min<1e-5)return;const levels=9;const eps=(max-min)*.0008;terrain.traverse(c=>{if(!(c instanceof THREE.Mesh))return;const g=c.geometry;const p=g.getAttribute('position');const idx=g.index;const get=(i:number)=>new THREE.Vector3(p.getX(i),p.getY(i),p.getZ(i));const tri=(a:number,b:number,cidx:number)=>{const A=get(a),B=get(b),C=get(cidx);for(let l=1;l<levels;l++){const level=min+(max-min)*l/levels;const pts:THREE.Vector3[]=[];[[A,B],[B,C],[C,A]].forEach(([u,v])=>{const du=u.y-level,dv=v.y-level;if((du<0&&dv>0)||(du>0&&dv<0)){const t=(level-u.y)/(v.y-u.y);pts.push(new THREE.Vector3().lerpVectors(u,v,t))}});if(pts.length===2){pts[0].y+=eps;pts[1].y+=eps;segments.push(...pts[0].toArray(),...pts[1].toArray())}}};if(idx)for(let i=0;i<idx.count;i+=3)tri(idx.getX(i),idx.getX(i+1),idx.getX(i+2));else for(let i=0;i<p.count;i+=3)tri(i,i+1,i+2)});const geom=new THREE.BufferGeometry();geom.setAttribute('position',new THREE.Float32BufferAttribute(segments,3));const mat=new THREE.LineBasicMaterial({color:'#7ca9ba',transparent:true,opacity:.48});setLines(new THREE.LineSegments(geom,mat));return()=>{geom.dispose();mat.dispose()};},[terrain,visible]);return lines?<primitive object={lines}/>:null}
function Stage({project,exaggeration,renderMode,mode,resetToken,preset,gridVisible,shadows,contours,onLoaded,onError,onClick}:any){const [terrain,setTerrain]=useState<THREE.Object3D|null>(null);const group=useRef<THREE.Group>(null);const loaded=useCallback((o:THREE.Object3D)=>{setTerrain(o);onLoaded(o)},[onLoaded]);return <><color attach="background" args={['#040a10']}/><ambientLight intensity={.62}/><hemisphereLight intensity={1.18} groundColor="#0a1821" color="#eefbff"/><directionalLight castShadow={shadows} position={[8,18,8]} intensity={3.5}/><directionalLight position={[-10,9,-12]} intensity={1.15}/><group ref={group} scale={[1,exaggeration,1]}><Terrain url={projectApi.getMeshUrl(project.project_id)} renderMode={renderMode} onLoaded={loaded} onError={onError} onClick={onClick}/><SceneGrid terrain={terrain} visible={gridVisible}/><Contours terrain={terrain} visible={contours}/></group>{terrain&&mode==='orbit'&&<CameraRig target={terrain} resetToken={resetToken} preset={preset}/>} {mode==='fly'&&<FlyControls movementSpeed={5.5} rollSpeed={.22} dragToLook/>}</>}
export function ViewerPanel({project,onInspection,inspection,history,meta,stats,gridVisible,setGridVisible,panelOpen,setPanelOpen}:Props){const [mode,setMode]=useState<ViewMode>('orbit'),[renderMode,setRenderMode]=useState<RenderMode>('rgb'),[exaggeration,setExaggeration]=useState(2.8),[preset,setPreset]=useState<CameraPreset>('isometric'),[resetToken,setResetToken]=useState(0),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[inspectionError,setInspectionError]=useState(''),[fullscreen,setFullscreen]=useState(false),[shadows,setShadows]=useState(true),[contours,setContours]=useState(false);const ref=useRef<HTMLDivElement>(null);const metadataRef=useRef<{width:number;height:number}|null>(null);const ready=!!project&&['READY','VALIDATED'].includes(project.state);
 useEffect(()=>{setLoaded(false);setError('');setInspectionError('');setResetToken(v=>v+1);metadataRef.current=null;onInspection?.(null);if(project)projectApi.getMetadata(project.project_id).then(m=>metadataRef.current={width:m.width,height:m.height}).catch(()=>{})},[project?.project_id]);
 useEffect(()=>{const h=()=>setFullscreen(document.fullscreenElement===ref.current);document.addEventListener('fullscreenchange',h);return()=>document.removeEventListener('fullscreenchange',h)},[]);
 const click=useCallback(async(i:THREE.Intersection)=>{if(!project||!i.uv)return;try{setInspectionError('');const md=metadataRef.current??await projectApi.getMetadata(project.project_id).then(m=>({width:m.width,height:m.height}));metadataRef.current=md;const pixelX=Math.round(THREE.MathUtils.clamp(i.uv.x,0,1)*(md.width-1));const pixelY=Math.round(THREE.MathUtils.clamp(1-i.uv.y,0,1)*(md.height-1));onInspection?.(await projectApi.inspectPixel(project.project_id,pixelX,pixelY))}catch(e:any){onInspection?.(null);setInspectionError(e?.response?.data?.detail||e?.message||'Point inspection failed.') }},[project,onInspection]);
 if(!ready||!project)return <div className="viewer-placeholder"><div className="empty-orb">◇</div><div className="empty-title">3D terrain workspace</div><div className="empty-copy">Upload an image and run reconstruction to open the interactive terrain engine.</div></div>;
 const fs=async()=>{if(!ref.current)return;if(document.fullscreenElement)await document.exitFullscreen().catch(()=>{});else await ref.current.requestFullscreen().catch(()=>{})};
 return <div className={`viewer-wrap ${fullscreen?'viewer-fullscreen':''}`} ref={ref}>
  <div className="viewer-header"><div><span className="eyebrow">RECONSTRUCTION ENGINE</span><h2>3D Terrain</h2><p>{project.reconstruction_mode==='metric'?'Metric calibrated DSM':'Relative DSM'} · click any surface to inspect elevation</p></div><div className="viewer-actions"><span className={`viewer-chip ${loaded?'ok':error?'bad':''}`}><i/>{loaded?'MODEL READY':error?'MODEL ERROR':'LOADING'}</span><button onClick={()=>setPanelOpen(!panelOpen)} title="Terrain controls">☰</button><button onClick={()=>setResetToken(v=>v+1)} title="Reset camera">↺</button><button onClick={fs} title="Fullscreen">⛶</button></div></div>
  <Canvas shadows dpr={[1,1.5]} camera={{position:[14,10,14],fov:42,near:.01,far:1000}} gl={{antialias:true,powerPreference:'high-performance'}} onPointerMissed={()=>{onInspection?.(null);setInspectionError('')}}><Stage project={project} exaggeration={exaggeration} renderMode={renderMode} mode={mode} resetToken={resetToken} preset={preset} gridVisible={gridVisible} shadows={shadows} contours={contours} onLoaded={(o:THREE.Object3D)=>{setLoaded(true);setError('')}} onError={(s:string)=>{setLoaded(false);setError(s)}} onClick={click}/></Canvas>
  {!loaded&&!error&&<div className="viewer-loading"><div className="spinner"/>Loading terrain engine…</div>}{error&&<div className="viewer-error"><strong>Terrain engine error</strong><span>{error}</span><button onClick={()=>{setError('');setResetToken(v=>v+1)}}>Retry</button></div>}{inspectionError&&<div className="viewer-inspection-error"><strong>Point inspection</strong><span>{inspectionError}</span></div>}
  {panelOpen&&<aside className="terrain-controls"><div className="terrain-control-head"><div><span className="eyebrow">TERRAIN TOOLS</span><h3>Scene controls</h3></div><button onClick={()=>setPanelOpen(false)}>×</button></div><ControlSection title="Layers"><LayerRow label="RGB texture" active={renderMode==='rgb'} onClick={()=>setRenderMode('rgb')}/><LayerRow label="Elevation surface" active={renderMode==='elevation'} onClick={()=>setRenderMode('elevation')}/><LayerRow label="Relief" active={renderMode==='relief'} onClick={()=>setRenderMode('relief')}/><LayerRow label="Slope" active={renderMode==='slope'} onClick={()=>setRenderMode('slope')}/><LayerRow label="Wireframe" active={renderMode==='wire'} onClick={()=>setRenderMode('wire')}/><ToggleRow label="Contours" value={contours} onChange={setContours}/><LayerRow label="Inspection points" active={!!inspection} onClick={()=>{}}/></ControlSection><ControlSection title="Spatial frame"><ToggleRow label="Show grid" value={gridVisible} onChange={setGridVisible}/><div className="small-note">Grid, axes and frame are attached to the terrain coordinate space.</div></ControlSection><ControlSection title="Terrain"><div className="range-row"><span>Vertical exaggeration</span><b>{exaggeration.toFixed(1)}×</b></div><input className="range" type="range" min="1" max="12" step=".1" value={exaggeration} onChange={e=>setExaggeration(+e.target.value)}/><ToggleRow label="Shadows" value={shadows} onChange={setShadows}/></ControlSection><ControlSection title="Camera"><div className="segmented">{(['isometric','top','front','side'] as CameraPreset[]).map(p=><button key={p} className={preset===p?'active':''} onClick={()=>{setPreset(p);setResetToken(v=>v+1)}}>{p==='isometric'?'Iso':p[0].toUpperCase()+p.slice(1)}</button>)}</div><div className="segmented two"><button className={mode==='orbit'?'active':''} onClick={()=>setMode('orbit')}>Orbit</button><button className={mode==='fly'?'active':''} onClick={()=>setMode('fly')}>Fly</button></div></ControlSection><ControlSection title="Navigation"><div className="nav-help"><span>Drag</span><b>Orbit</b><span>Wheel</span><b>Zoom</b><span>WASD</span><b>Fly</b><span>Click</span><b>Inspect</b></div></ControlSection></aside>}
  <aside className="terrain-inspector"><div className="terrain-inspector-head"><span className="eyebrow">INSPECTOR</span><b>{inspection?'POINT':'SURFACE'}</b></div>{inspection?<><div className="point-elevation"><span>Elevation</span><strong>{fmt(inspection.elevation)} <small>{inspection.unit||'m'}</small></strong></div><div className="terrain-info-grid"><Info label="Relative" value={inspection.relative_height!==undefined?fmt(inspection.relative_height):'—'}/><Info label="Slope" value={inspection.slope!==undefined?`${fmt(inspection.slope)}°`:'—'}/><Info label="Pixel" value={`${inspection.pixel_x??'—'}, ${inspection.pixel_y??'—'}`}/><Info label="X" value={fmt(inspection.x,3)}/><Info label="Y" value={fmt(inspection.y,3)}/></div><div className="inspector-history"><span>RECENT POINTS</span>{(history?.inspection_history||[]).slice(0,5).map((p:any,i:number)=><div key={i}><b>P{i+1}</b><strong>{fmt(p.elevation)} {p.unit||'m'}</strong></div>)}</div></>:<><div className="surface-stat"><span>Min</span><b>{stats?`${fmt(stats.min_elevation)} ${stats.unit}`:'—'}</b></div><div className="surface-stat"><span>Max</span><b>{stats?`${fmt(stats.max_elevation)} ${stats.unit}`:'—'}</b></div><div className="surface-stat"><span>Mean</span><b>{stats?`${fmt(stats.mean_elevation)} ${stats.unit}`:'—'}</b></div><div className="surface-stat"><span>Coverage</span><b>{stats?`${fmt(stats.valid_pixel_percentage,1)}%`:'—'}</b></div><div className="terrain-spatial"><span>SPATIAL METADATA</span><b>{meta?.crs||'Not georeferenced'}</b><small>{meta?`${meta.width} × ${meta.height} · ${meta.resolution?fmt(meta.resolution[0],2):'—'} m pixels`:'—'}</small></div><div className="inspector-history"><span>VALIDATION</span><div><b>RMSE</b><strong>{history?.validation_history?.[0]?`${fmt(history.validation_history[0].rmse)} m`:'—'}</strong></div><div><b>R²</b><strong>{history?.validation_history?.[0]?fmt(history.validation_history[0].r2,3):'—'}</strong></div></div></>}</aside>
  <div className="viewer-bottom"><span><b>Drag</b> orbit</span><span><b>Wheel</b> zoom</span><span><b>Click</b> inspect</span><span><b>WASD</b> fly</span><span className="viewer-state">{project.reconstruction_mode==='metric'?'METRIC':'RELATIVE'} · {gridVisible?'GRID ON':'GRID OFF'} · {contours?'CONTOURS ON':'CONTOURS OFF'}</span></div>
 </div>;
}
function ControlSection({title,children}:{title:string;children:any}){return <section className="control-section"><div className="control-title">{title}</div>{children}</section>}
function LayerRow({label,active,onClick}:{label:string;active:boolean;onClick:()=>void}){return <button className={`layer-row ${active?'active':''}`} onClick={onClick}><i/>{label}<span>{active?'●':'○'}</span></button>}
function ToggleRow({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <label className="toggle-row"><span>{label}</span><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/><i/></label>}
function Info({label,value}:{label:string;value:string}){return <div><span>{label}</span><b>{value}</b></div>}
function fmt(v:any,d=2){return typeof v==='number'&&Number.isFinite(v)?v.toFixed(d):'—'}
