export type ProjectState='NEW'|'UPLOADED'|'PREPROCESSING'|'DEPTH_ESTIMATION'|'CALIBRATING'|'DSM_GENERATION'|'MESH_GENERATION'|'READY'|'VALIDATED'|'FAILED';
export type CalibrationType='none'|'dem'|'gcp';
export type ReconstructionMode='relative'|'metric';
export interface Project { project_id:string; name:string; state:ProjectState; progress:number; message:string; created_at:string; updated_at:string; is_georeferenced:boolean; calibration_type:CalibrationType; reconstruction_mode:ReconstructionMode; error?:string; job_id?:string; job_state?:string; started_at?:number; completed_at?:number; progress_stage?:string; }
export interface ImageMetadata { filename:string;width:number;height:number;channels:number;dtype:string;file_size_bytes:number;is_georeferenced:boolean;crs?:string;epsg?:number;bounds?:{left:number;bottom:number;right:number;top:number};resolution?:[number,number];transform?:number[];nodata?:number;band_count?:number; }
export interface DSMStatistics { min_elevation:number;max_elevation:number;mean_elevation:number;median_elevation:number;std_elevation:number;elevation_range:number;valid_pixel_count:number;total_pixel_count:number;valid_pixel_percentage:number;is_metric:boolean;unit:string;slope_min?:number;slope_max?:number;slope_mean?:number;resolution_x?:number;resolution_y?:number; }
export interface GCPInput {pixel_x:number;pixel_y:number;reference_elevation:number;}
export interface AnalysisRun {run_id:string;method?:string;created_at:string;reference_file?:string;scale?:number;offset?:number;valid_pixel_count?:number;rmse?:number;mae?:number;residual_mean?:number;residual_std?:number;r2?:number;pearson_correlation?:number;bias?:number;std_error?:number;valid_pixel_percentage?:number;gcps?:GCPInput[];split?:any;calibration_run_id?:string;}
export interface ValidationMetrics {mae:number;rmse:number;pearson_correlation:number;r2:number;bias:number;std_error:number;p95_abs_error:number;max_abs_error:number;valid_pixel_count:number;valid_pixel_percentage:number;}
export interface TerrainInspection {x:number;y:number;elevation:number;relative_height?:number;slope?:number;unit?:string;pixel_x?:number;pixel_y?:number;created_at?:string;}
export interface HistoryResponse {calibration_history:AnalysisRun[];validation_history:AnalysisRun[];reconstruction_history:any[];inspection_history:TerrainInspection[];current_calibration_id?:string;current_validation_id?:string;}
export interface ProcessSettings {model_name:string;inference_resolution:number;tile_size:number;tile_overlap:number;edge_refinement:boolean;terrain_smoothing:boolean;}
